// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGpi_R9SrQm6RU6wV5xf4vW7wb-NqCxag',
    appId: '1:758364743658:web:6ee894348bd00850ebb493',
    messagingSenderId: '758364743658',
    projectId: 'fluentiq-af8ad',
    authDomain: 'fluentiq-af8ad.firebaseapp.com',
    storageBucket: 'fluentiq-af8ad.appspot.com',
    measurementId: 'G-FXCWY4BN6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2wQ4OPlT6rwv1Tziw06s-Ah-kCBVXmbA',
    appId: '1:758364743658:android:9d14b80d3764a2dfebb493',
    messagingSenderId: '758364743658',
    projectId: 'fluentiq-af8ad',
    storageBucket: 'fluentiq-af8ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB0-APrgJ6LS_orzNC5bm4bqJuxTBQKpg',
    appId: '1:758364743658:ios:0c49063379230c6aebb493',
    messagingSenderId: '758364743658',
    projectId: 'fluentiq-af8ad',
    storageBucket: 'fluentiq-af8ad.appspot.com',
    iosBundleId: 'com.hub.fluentiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB0-APrgJ6LS_orzNC5bm4bqJuxTBQKpg',
    appId: '1:758364743658:ios:0c49063379230c6aebb493',
    messagingSenderId: '758364743658',
    projectId: 'fluentiq-af8ad',
    storageBucket: 'fluentiq-af8ad.appspot.com',
    iosBundleId: 'com.hub.fluentiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGpi_R9SrQm6RU6wV5xf4vW7wb-NqCxag',
    appId: '1:758364743658:web:6276959c6ae485faebb493',
    messagingSenderId: '758364743658',
    projectId: 'fluentiq-af8ad',
    authDomain: 'fluentiq-af8ad.firebaseapp.com',
    storageBucket: 'fluentiq-af8ad.appspot.com',
    measurementId: 'G-3E522C1DQ6',
  );
}
